### ISSUE TITLE
Add ability to use custom T4 template when generating client code

### ISSUE THREAD

**Issue by dziedrius** [NSwag/NSwag#273]
Currently I could not find ability to customize T4 template without using custom NSwag build and there are many cases when using base class or partial method does not cover the extensibility needs.

Swagger codegen allows to use custom templates, but it has other issues (java runtime :)

If it is not possible to use custom T4 template directly from command line, may be it would be possible to load compiled T4 template as dll and use it such way.

**Comment by rsuter** [comment]
Currently you can provide your own TemplateFactory and render your own code... but it cannot be used in the command line because there is no way to load external DLLs into the process and instantiate a template factory. However we could add a new cmd line parameters: 

- ExtensionAssemblies: Assemblies which are loaded into the cmd line process
- TemplateFactoryType: The full type name which is instantiated and used as template factory (loaded from an extension assembly)

This way you can implement the template factory and then use it in the cmd line tool. 
What do you think?

**Comment by rsuter** [comment]
Another option would be to use another template engine which can also compile/run templates at runtime, see https://github.com/NSwag/NSwag/issues/263 
But then you can only change the template but not the logic - which may be limiting in some scenarios...

**Comment by dziedrius** [comment]
Your suggestion regarding additional cmd line parameters to provide own extension assembly with custom template factory type seems good to me, it should cover most cases that I can think of.

**Comment by dziedrius** [comment]
Looks like even using NSwag not from command line it is not possible to use custom template, as I need pass into template's constructor instance ClientTemplateModel, which is internal :(

`NSwag.CodeGeneration.CodeGenerators.CSharp.Models
{
  internal class ClientTemplateModel
`

**Comment by rsuter** [comment]
ClientTemplateModel and the other models will be public in the next version...

**Comment by rsuter** [comment]
Please write your own simple cmd line tool until this feature has been implemented.

**Comment by RSuter** [comment]
See https://github.com/NSwag/NSwag/issues/263

**Comment by RSuter** [comment]
https://github.com/RSuter/NSwag/wiki/Templates
