### ISSUE TITLE
Type and format are missing on some parameters in my swagger output

### ISSUE THREAD

**Issue by langboost** [NSwag/NSwag#286]
I am getting a JSON schema error on the first parameter (but not the second one) when I look at it using the live demo on http://editor.swagger.io

"parameters": [
          {
            "name": "scopeType",
            "in": "query",
            "required": true,
            "x-nullable": false,
            "$ref": "#/definitions/WsScopeType"
          },
          {
            "type": "integer",
            "name": "scopeId",
            "in": "query",
            "required": true,
            "x-nullable": false,
            "format": "long"
          }
        ],

I want to collect more information for you to troubleshoot this error, but I'm not familiar enough yet with your code base. Do you have any suggestions on what to try / look at?

I think the C# type it's choking on may be an enum.

**Comment by langboost** [comment]
Generated via MSBuild
<Exec Command="$(NSwagExe) webapi2swagger /assembly:$(OutDir)/$(AssemblyName).dll /output:Documentation\$(AssemblyName).Swagger.json" />

**Comment by rsuter** [comment]
What error?

**Comment by langboost** [comment]
Swagger Error
Not a valid parameter definition
Jump to line 1397
Details
 Object
code:  "ONE_OF_MISSING"
 params: Array [0]
message:  "Not a valid parameter definition"
 path: Array [5]
0:  "paths"
1:  "/api/Tenant/SetScope"
2:  "post"
3:  "parameters"
4:  "0"
schemaId:  "http://swagger.io/v2/schema.json#"
 inner: Array [2]
 0: Object
code:  "ONE_OF_MISSING"
 params: Array [0]
message:  "Data does not match any schemas from 'oneOf'"
 path: Array [5]
 inner: Array [2]
 1: Object
code:  "OBJECT_MISSING_REQUIRED_PROPERTY"
 params: Array [1]
message:  "Missing required property: $ref"
 path: Array [5]
level: 900
type:  "Swagger Error"
description:  "Not a valid parameter definition"
lineNumber: 1397

**Comment by rsuter** [comment]
Can you post the full swagger spec?

**Comment by rsuter** [comment]
I think the $ref is not allowed here...

**Comment by rsuter** [comment]
Ok, the problem is that the parameter type "Query" only allows primitive types, and enum is considered primitive... the problem is that refs are not allowed together with other properties. 

See https://github.com/OAI/OpenAPI-Specification/issues/300

However it seems that in the next version, the "schema" property is also allowed for other parameter types and we can reference the enum this way: 

https://github.com/OAI/OpenAPI-Specification/pull/654

However this is/may not be compatible with Swagger 2.0 and the editors... but for now I'll change to that because its more valid then the current output...

**Comment by rsuter** [comment]
The problem is here: 

![image](https://cloud.githubusercontent.com/assets/2603405/18404583/b361484e-76eb-11e6-8490-1fffee245f65.png)

**Comment by rsuter** [comment]
Added this fix/hack: https://github.com/NSwag/NSwag/commit/66336a3ceaa9b8919a74a502ac4dfb5cdb772247

As you can see there is no simple solution. There are two options: 

- Be Swagger 2.0 compliant: But then enums have to be redefined (because they cannot be referenced) and a matching algorithm is needed so that enums are not generated twice (when generating client code)
- Use Swagger vNext for this (be non-compliant): Use "schema" attribute (as in the latest commit). This behavior can be implemented by other clients without breaking compatibility with older specs

Please clone the latest commit from "master" and try yourself, maybe its fine now?

The parameter should now look like: 

```
[{
	"name": "scopeType",
	"in": "query",
	"required": true,
	"x-nullable": false,
	"schema": {
		"$ref": "#/definitions/WsScopeType"
	}
},
{
	"type": "integer",
	"name": "scopeId",
	"in": "query",
	"required": true,
	"x-nullable": false,
	"format": "long"
}]
```

**Comment by langboost** [comment]
I was able to check your solution this morning. It looks like it's sticking both in there now:
"parameters": [
          {
            "name": "scopeType",
            "in": "query",
            "required": true,
            "schema": {
              "$ref": "#/definitions/WsScopeType"
            },
            "x-nullable": false,
            "$ref": "#/definitions/WsScopeType"
          },
          {
            "type": "integer",
            "name": "scopeId",
            "in": "query",
            "required": true,
            "x-nullable": false,
            "format": "long"
          }
        ],

**Comment by rsuter** [comment]
With latest commits, a parameter should look like: 

        "parameters": [
          {
            "name": "gender",
            "in": "query",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Gender"
            },
            "x-nullable": true
          }
        ],

**Comment by rsuter** [comment]
I'm not sure if this is the best solution...

**Comment by rsuter** [comment]
Is this ok? (this is a compromise we have to do with the Swagger 2.0 specification).

**Comment by langboost** [comment]
I understand the need to compromise. This helps me out a lot. Thanks for making the change!
