### ISSUE TITLE
Swagger specification not validated by the schema.

### ISSUE THREAD

**Issue by evrardp** [NSwag/NSwag#39]
Dear,

I'm doing some tests with the swagger specification generation from a web api assembly written in C#.
I take the json output file generated by NSwagStudio, and I try to validate it against the Swagger 2.0 schema (https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json).

It fails and give me these errors :

Property 'Get' has not been defined and the schema does not allow additional properties.  Property 'typeName' has not been defined and the schema does not allow additional properties.  Property 'enumNames' has not been defined and the schema does not allow additional properties.  

When using the Swagger Editor online, I receive the same messages.

Could you please tell me what I'm doing wrong or how can I avoid this ?

Thanks for the info.

**Comment by rsuter** [comment]
The problem here is that NSwag and NJsonSchema define additional properties to generate better code: 

- `typeName`: Stores the original class name of the schema. If this property is missing, the class name is unknown and must be derived from the property or randomly generated. 
- `enumNames`: An enum in JSON Schema defines only the allowed values (i.e. 0,1,2 in a C# enum with integer type [default]) but not the enum names. This property has been added so that the correct enum can be generated. Otherwise the names would be something like `name_0`, `name_1`, etc.
- `Get`: Where did you get this validation error?

**Comment by rallister** [comment]
"Get: Where did you get this validation error?" 
I think it would be an operations.

Postman does not load Upper case operations Get/Post either. I had to make the whole payload lowercase because could not convert dictionary keys to lower for these operations ( service.Paths because it's enum and not a string).

**Comment by aws-na-ss-usplu** [comment]
Novice: Our very small two cents **_;-)_**

We currently develop solutions in two worlds… LoopBack/Node.js & WebApi/Asp.net

 We would love to have a solution that complements each others interpretation of the concepts around

- Generic Extensions for Enum
- Implement of Enum
- Solution path to transition from Swagger Extension to first class member of Swagger 2.x schema

We currently use swagger to generate both client/server code for LoopBack & .NET, and client code in Java and PHP.  When it comes to **Enum** and **Additional Properties** we have to deal with exceptions because like HTML specs each community is interpreting the specifications a little differently rather than each community discussing the discrepancy to improve the understanding and interpreting of the Swagger Specs.

Here is Swagger API discussion around ENUMs for C-Sharp

- [C# - Lists of enums not properly generated #2714](https://github.com/swagger-api/swagger-codegen/issues/2714)

Here is StrongLooop / Loopback discussion around Enums 

- [New type: ENUM #1321](https://github.com/strongloop/loopback/issues/1321#issuecomment-216868272)

Here is how AutoRest community is currently dealing with Enums with AutoRest

- [Azure's AutoRest Generic Extensions](https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md) 
- [AutoRest x-ms-enum](https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md#x-ms-enum)
- [Enums with x-ms-enum definition](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md#Enum-x-ms-enum)
- [AutoRest Enum Github Issue#393](https://github.com/Azure/autorest/pull/393/files)

We still need to investigate where the StrongLoops/ IBM thoughts on implementing Enum, and we plan to review shortly.

We just propose that all participants in providing a Swagger Code Generators to deal with Enum to converge on a solution rather than have a lot of silo implementations of swagger generic extensions for Enum.

We have investigated the following code generators to date.  Non have a consist implementation to deal with **Additional Properties** or **Enum**

- [Azure AutoRest](https://github.com/Azure/autorest)
- [NSwag ](http://nswag.org)
- [Swagger-API Online Editor](http://editor.swagger.io)
- [Swagger-API CodeGen](https://github.com/swagger-api/swagger-codegen )
- [Loopback Swagger Generator](https://docs.strongloop.com/display/public/LB/Swagger+generator ) 

Appreciate feedback, concerns and issues with our thoughts…

**Comment by rsuter** [comment]
The upper cased HTTP methods are now serialized lower case: https://github.com/NSwag/NSwag/commit/e0d351a54bb6bb607edb3a218044f82504b11635

The other properties cannot be removed, because they are needed for proper code generation (extension to JSON Schema, because an equivalent property is missing). 

@aws-na-ss-usplu: The problem is mainly JSON Schema and the discrepancy between JSON and C#/TypeScript... there will not be a good solution in the foreseeable future - people are still discussing the problems and they don't seem to come to an agreement soon...
