### ISSUE TITLE
I am getting error - Nswag.CodeGenerator does not have strong name. 

### ISSUE THREAD

**Issue by waniguanxi** [NSwag/NSwag#60]
I am getting this error. When I tried to download code and get this signed, it started complaining about NJsonSchema.CodeGenerator is not signed and so no. I don't want to keep on signing all the assemblies.

What do you think would be better way to get around this?

**Comment by rsuter** [comment]
You want to sign NSwag.CodeGenerator?

**Comment by waniguanxi** [comment]
I want a version of NSwag.CodeGenerator that has strong name. I see there is a key when I downloaded the code. I was using that same to get this one strong name as well. NSwag.Core is having strong name.

**Comment by rsuter** [comment]
Its not possible, because the project depends from [Antlr4.StringTemplate](https://www.nuget.org/packages/Antlr4.StringTemplate/) and it does not have a strong name... In the future, I have to switch to another template engine library but I couldn't find one that fits my needs yet (PCL, strong name, good syntax, etc...) Signing NJsonSchema.CodeGenerator is also not possible because it uses the same template engine... As soon as the template engine is replaced, everything can be signed...

**Comment by waniguanxi** [comment]
:( ok. I was trying to use NSwag to generate POCO classes for our webAPIs ... but all our assemblies are strong named. I might have to wait or use another alternative. Do you know of any?

**Comment by waniguanxi** [comment]
Thanks for you reply.

**Comment by rsuter** [comment]
Can't you use the command line tools and pass your Web API dlls to it?

**Comment by rsuter** [comment]
Or how do you want to use NSwag in your environment?
