### ISSUE TITLE
How to work with date objects in generated TypeScript client

### ISSUE THREAD

**Issue by berhir** [NSwag/NSwag#61]
I used NSwag to generate a TypeScript Angular 2 client for my .NET Web API service via a swagger.json file.
Some of my DTOs contain date fields that are formatted as ISO date strings in json.

The swagger definition of the fields look like this:
```
"BeginDateTime": {
    "format": "date-time",
    "type": "string"
},
```
This is the field in the generated TypeScript interface:
```
BeginDateTime?: Date;
```
And the JSON object:
```
{
    ...,
    "BeginDateTime": "2016-04-19T18:03:40.887",
    ...
}
```

The problem is that `Json.parse()` does not convert the date string to a JavaScript date object. When I want to use date specific functions like `dto.BeginDateTime.getHours()` it's no problem at compile time but crashes at runtime.

I can also not simply do a `new Date(dto.BeginDateTime)` because it would cause a TypeScript compile error. The workaround is `new Date(<any>dto.BeginDateTime)` and that's not the way we should use TypeScript.

What is your preferred way to handle this? Why does the generated client not use a reviver function to parse the date? Or at least allow me to inject a function or service that can do this.

**Comment by rsuter** [comment]
DateTime is a big problem in JSON because there is no standard way to serialize them. The generated DTOs are just interfaces and cannot implement conversion methods or other logic to convert to a date. A way to fix this is to instead of serializing to `"2016-04-19T18:03:40.887"` serialize to `date(...)`. I think there is an option in Json.NET to do this... I have to investigate further and check what the default behavior of Json.NET is...

**Comment by rsuter** [comment]
If you serialize with `JavaScriptDateTimeConverter` then datetimes are serialized to `new Date(...)` and then the interfaces are correct... but I don't like having JavaScript in the JSON data...

http://james.newtonking.com/archive/2009/02/20/good-date-times-with-json-net

The other option is currently to add a setting to generate datetime as string... but this is also not very good. 

The best solution would be to generate classes instead of interfaces and convert datetime properties from string to Date (if necessary). This is much more time consuming to implement but on the roadmap: https://github.com/NJsonSchema/NJsonSchema/issues/43

**Comment by rsuter** [comment]
Another option is to add support for `"\/Date(1198908717056)\/"` in the generated client classes so that Json.NET standard serialization works correctly: 
http://weblogs.asp.net/bleroy/dates-and-json

**Comment by berhir** [comment]
Thank you for your answers!
I know it's a general problem in JSON, but I hoped there is a way to handle this with NSwag. Like injecting a reviver function that can be used by the `JSON.parse(text[, reviver])` function.

We use ISO date format because it is used by all big players and is therefor a de facto standard.

I will keep an eye on the implementation with classes and use a workaround in the meantime.

**Comment by rsuter** [comment]
Currently, the Angular 2 template just uses the `response.json()` method to get the JSON. 
https://angular.io/docs/ts/latest/api/http/Response-class.html

We could change this to: 
```
var text = response.text();
var data = JSON.parse(text, this.reviver);
```
so that you can implement your reviver...

**Comment by rsuter** [comment]
Ok, I've added some new bugs: 

https://github.com/NSwag/NSwag/issues/62
https://github.com/NJsonSchema/NJsonSchema/issues/55

**Comment by rsuter** [comment]
Ok, the Angular 2 tpl now accepts a reviver function and `"\/Date(...)\/"` is supported for all templates... 

https://github.com/NSwag/NSwag/commit/c71f2ae9615c987be45c732f73c948a714028a73

You can now inject the ISO date time reviver function here: 
http://stackoverflow.com/questions/1792865/how-to-use-json-parse-reviver-parameter-to-parse-date-string

More info in the issue here: https://github.com/NSwag/NSwag/issues/62

**Comment by rsuter** [comment]
You can use the reviver here for converting ISO datetime strings: 
http://stackoverflow.com/questions/1792865/how-to-use-json-parse-reviver-parameter-to-parse-date-string

**Comment by berhir** [comment]
Thank you for the prompt implementation. Reviver is now working for me!
