### ISSUE TITLE
Latest nswag npm package (9.5) fails on Linux (ubuntu/mint)

### ISSUE THREAD

**Issue by empedia** [NSwag/NSwag#613]
**Steps to reproduce:**

Install .net core 

Install nswag using sudo install -g nswag

Run nswag from command line
**Expected result**
nswag cli runs

**Actual result**
/usr/bin.env: 'node/r': No such file or directory

The problem seems to be that the nswag.js file is using windows line endings which are not interpreted correctly on Linux. 

I have confirmed that changing line endings to support Linux fixes the problem.

**Comment by rsuter** [comment]
Should be fixed with v9.5.1

**Comment by grovesNL** [comment]
@rsuter: Could we avoid setting everything to binary? Instead we could specify `text=auto` to automatically convert text files to LF? i.e. use a combination of the C#, Visual Studio and Web templates from here https://github.com/alexkaratarakis/gitattributes

Currently it's hard to make pull requests because the commit line endings will depend on each user's git autocrlf setting. I didn't realize why my diffs were unusual until I saw the recent CR commit.
