### ISSUE TITLE
[ts] Duplicate function implementation.

### ISSUE THREAD

**Issue by balazserdos** [NSwag/NSwag#756]
When I'm generation a client using NSwagStudio I get the following issue:
If there is 2 HTTP method declaration in the swagger file then NSwag generates 2 different functions with the same name.
Let's say:
```
  "paths": {
    "/pet": {
      "post": {
      ...
      },
      "put": {
      },
}
```
will be 
```
    pet(body: Pet): Promise<void> {
...
}
    pet(body: Pet): Promise<void> {
}
```
cause the following issue:
[ts] Duplicate function implementation.

Could you tell me what am I doing wrong? Thanks :)

Used config:

![image](https://cloud.githubusercontent.com/assets/20303564/25704490/ef6320e4-30d9-11e7-98de-8336ace929d4.png)

**Comment by rsuter** [comment]
The problem is the selected "Operation Generation Mode" (best is ID-based): Because the path "/pet" has two HTTP methods, the method gets generated twice (MultipleClientsFromPathSegments only uses the path to generate the method name)

**Comment by balazserdos** [comment]
yep, it was the problem. Thank you so much :)

**Comment by viveknuna** [comment]
How to open this configuration UI, I'm able to see the only service.config.nswag file with a text `"operationGenerationMode": "MultipleClientsFromPathSegments"`, I'm also facing the same issue so what should I get value for "operationGenerationMode" instead of "MultipleClientsFromPathSegments",  or do I need to delete this line?
Is there any side effect of this ?

**Comment by RSuter** [comment]
See https://github.com/RSuter/NSwag/blob/master/src/NSwag.Commands/Commands/CodeGeneration/OperationGenerationMode.cs
