### ISSUE TITLE
Missing entity

### ISSUE THREAD

**Issue by lucassp** [NSwag/NSwag#812]
When generating the Swagger API json file using NSwag 11.1.2 (latest stable in NuGet) from a WebAPI assembly, one of my entities is missing all fields. Doing the same thing using NSwag 10.6.0 the fields are extracted correctly.

It looks like the bug is there since 11.0.0

**Comment by RSuter** [comment]
Can you post a sample class/controller?

**Comment by lucassp** [comment]
The controller method is pretty simple:

```CSharp
[Route("includingElements"), HttpGet]
[ClaimAuthorize(Roles = AppRoles.Administrator)]
public async Task<IEnumerable<BusinessCategory>> GetCategoriesIncludingElements()
{
            var calculator = CalculatorFactory.GetAccessRightsCalculator();
            var categories = await calculator.CalculateElementsForCategories();
            return categories;}
```
and the entities are

```CSharp

```

**Comment by RSuter** [comment]
**Missing properties:** We are now using the Newtonsoft.Json ContractResolver to iterate through the properties (instead of own reflection). The idea is to produce a schema which is more in sync with the effectively serialized data... It seems that interfaces are handled differently - we have to check where this is coming from. (this must be fixed in http://njsonschema.org)

**Pascal cased properties:** You can change this with the DefalutPropertyNameHandling (set to CamelCase)

**Comment by RSuter** [comment]
TODO: Add setting to command and UI

**Comment by lucassp** [comment]
Did you get to have a look at why the interfaces are not serialized correctly? Thanks!
